config_project: All-Projects
config_project_branch: refs/meta/config
config_filename: automerger_config.yaml
global_keys:
- always_blank_merge
- blank_merge
- manifest
config_option_keys:
- manifest
- merge_all
- merge_manifest
- set_projects
- ignore_projects
- add_projects
