config_project: tools/automerger
config_project_branch: master
config_filename: config.yaml
global_keys:
- always_blank_merge
- blank_merge
- manifest
config_option_keys:
- manifest
- merge_all
- merge_manifest
- set_projects
- ignore_projects
- add_projects
- ignore_source_manifest